language: go

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm

env:
# needed for the snap pipe:
- PATH=/snap/bin:$PATH

install:
# needed for the snap pipe:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

# calls goreleaser
deploy:
- provider: script
  script: 
   - go test -v -covermode=count -coverprofile=coverage.out
   - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALL_TOKEN
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux