language: go

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm

env:
# needed for the snap pipe:
- PATH=/snap/bin:$PATH
- DEP_VERSION=v0.4.1

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
# needed for the snap pipe:
- dep ensure
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

# calls goreleaser
deploy:
- provider: script
  script: 
   - go test -v -covermode=count -coverprofile=coverage.out
   - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALL_TOKEN
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux